service_name: demo-java-service
build_path: demo-java-service
dockerfile_path: demo-java-service/Dockerfile
image_repo: acr-dh-registry.eu-central-1.cr.aliyuncs.com/agent/demo-java-service
gitops_repo: https://github.com/wgh9626/agent.git
gitops_branch: main
gitops_manifest: demo-java-service-gitops/apps/test/deployment.yaml
argocd_app: agent
image_tag_strategy: git-build-number
harbor_credentials_id: harbor
gitops_git_credentials_id: gitops
